on: [push]

name: GettingStarted_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.4e08a17f-5ac7-47fb-a81f-0e02d2f05140 }}
            password: ${{ secrets.Il~8Q~5WVB-haY7LlBkJuo66D-qmM9mtO7UB5atD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_CREDENTIALS }}:${{ github.run_number }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_CREDENTIALS }}:${{ github.run_number }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.container_registry }}
            dns-name-label: ${{ secrets.container_registry }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_CREDENTIALS }}:${{ github.run_number }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.4e08a17f-5ac7-47fb-a81f-0e02d2f05140 }}
            registry-password: ${{ secrets.Il~8Q~5WVB-haY7LlBkJuo66D-qmM9mtO7UB5atD }}
            name: getting-started-github
            location: 'west europe'
            ports: '3000'
            
            
